version: '3'

volumes:
  www-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/html
  mariadb-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/mariadb
  elastic-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/elastic
  redis-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/redis

services:
#  sshd:
#    image: hermsi/alpine-sshd
#    container_name: ${COMPOSE_PROJECT_NAME}-SSH
#    environment:
#      ROOT_PASSWORD: ${ROOT_PASSWORD}
#    ports:
#      - "${SSH_PORT}:22"
#    volumes:
#      - www-data:/var/www/html

  python:
    build:
      context: ./
      args:
        PYTHON_TAG: ${PYTHON_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-Python
    environment:
      DB_HOST: mysql
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_NAME: ${MARIADB_DATABASE}
      DB_ENGINE: ${DB_ENGINE}
    volumes:
    - www-data:/usr/src/app:cached

    networks:
      - default
      - proxy

    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=${HOSTRULE}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}_SVC
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}_Header
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_SVC.loadBalancer.server.port=80
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_Header.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_Header.headers.customrequestheaders.X-Forwarded-Ssl=on
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_Header.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.docker.network=traefik_proxy

  mysql:
    image: mariadb:10.5
    container_name: ${COMPOSE_PROJECT_NAME}-MariaDB
    # command für mysql 8.x
    # command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # command für mariadb
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./configs/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TIMEZONE}

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-Redis
    volumes:
      - redis-data:/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: ${COMPOSE_PROJECT_NAME}-Elastic
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    expose:
      - 9200
      - 9300

networks:
  proxy:
    external:
      name: ${PROXY_NETWORK}
